apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ai-core-proxy.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.image.repository (default "" .Values.dockerRegistry.username) (default "" .Values.dockerRegistry.password) (printf "%s:%s" (default "" .Values.dockerRegistry.username) (default "" .Values.dockerRegistry.password) | b64enc) | b64enc }}
