{{- if and .Values.aiCoreProxy.enabled .Values.aiCoreProxy.imagePullSecrets }}
{{- if .Values.dockerRegistry }}
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: ai-core-proxy
    {{- include "bolt.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.aiCoreProxy.image.repository .Values.dockerRegistry.username .Values.dockerRegistry.password (printf "%s:%s" .Values.dockerRegistry.username .Values.dockerRegistry.password | b64enc) | b64enc }}
{{- end }}
{{- end }}
